#!/usr/bin/env bash
# Expose this dev container as an SSH target for Orca (https://www.onorca.dev/docs/ssh).
#
# Orca is the SSH *client*: its Settings -> SSH targets describe hosts where it
# creates worktrees and runs agents. This container plays the remote host, so the
# script below stands up an sshd on port 2222 that devcontainer.json forwards to
# the laptop. Idempotent: safe to run from post-start.sh on every container start.
set -euo pipefail

PORT=2222
USER_NAME="$(id -un)"
HOME_DIR="$(getent passwd "$USER_NAME" | cut -d: -f6)"
# Dedicated volume (see devcontainer.json): Orca's SSH state lives here, NOT in the
# shared home volume. Parked there, a container recreate could quietly hand out a fresh
# keypair and break the key the laptop had copied; a fixed-name volume keeps host keys
# and authorized_keys stable across rebuilds and independent of the home mount.
SSH_ROOT="$HOME_DIR/.orca-ssh"
HOST_KEY_DIR="$SSH_ROOT/host_keys"
# Named to match the identity path Orca expects on the laptop (~/.ssh/orca_griffdive).
CLIENT_KEY="$SSH_ROOT/orca_griffdive"
AUTHORIZED_KEYS="$SSH_ROOT/authorized_keys"
DROPIN=/etc/ssh/sshd_config.d/10-griffdive-orca.conf
# Optional laptop public key: drop it here to authorize without moving a private key.
EXTRA_PUBKEY="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/orca.pub"
LEGACY_SSH_DIR="$HOME_DIR/.ssh"

# A fresh named volume mounts root-owned, so claim it before writing keys.
if [ ! -d "$SSH_ROOT" ] || [ ! -w "$SSH_ROOT" ]; then
  sudo mkdir -p "$SSH_ROOT"
  sudo chown "$USER_NAME" "$SSH_ROOT"
fi
chmod 700 "$SSH_ROOT"
mkdir -p "$HOST_KEY_DIR"
chmod 700 "$HOST_KEY_DIR"

# Adopt key material from the pre-volume layout (~/.ssh) by COPY, so introducing the
# volume does not rotate keys an Orca target has already pinned: on the first start
# after the volume exists it is empty, and this restores the same keypair. The legacy
# copy doubles as a seed if the volume is ever recreated; once the volume holds keys
# the seed is ignored, so it can never override live state.
for suffix in '' '.pub'; do
  for old in orca_ed25519 orca_griffdive; do
    if [ -f "$LEGACY_SSH_DIR/$old$suffix" ] && [ ! -f "$CLIENT_KEY$suffix" ]; then
      cp -a "$LEGACY_SSH_DIR/$old$suffix" "$CLIENT_KEY$suffix"
    fi
  done
done

# --- Host keys: generated once in the Orca volume, then exposed at sshd's default
# paths via symlinks (sshd_config.d can add settings but cannot unset HostKey lines).
for type in ed25519 rsa ecdsa; do
  key="$HOST_KEY_DIR/ssh_host_${type}_key"
  legacy="$LEGACY_SSH_DIR/host_keys/ssh_host_${type}_key"
  if [ ! -f "$key" ] && [ -f "$legacy" ]; then
    cp -a "$legacy" "$key"
    cp -a "$legacy.pub" "$key.pub"
  fi
  [ -f "$key" ] || ssh-keygen -q -t "$type" -N '' -f "$key" -C "griffdive devcontainer host key"
  chmod 600 "$key"
  chmod 644 "$key.pub"
  sudo ln -sfn "$key" "/etc/ssh/ssh_host_${type}_key"
  sudo ln -sfn "$key.pub" "/etc/ssh/ssh_host_${type}_key.pub"
done

# --- Client key Orca authenticates with. Generated without a passphrase so the target
# connects unattended; add one with `ssh-keygen -p -f ~/.orca-ssh/orca_griffdive`.
if [ ! -f "$CLIENT_KEY" ]; then
  ssh-keygen -q -t ed25519 -N '' -f "$CLIENT_KEY" -C "orca@griffdive-devcontainer"
fi
chmod 600 "$CLIENT_KEY"
chmod 644 "$CLIENT_KEY.pub"

# The laptop's own public key (EXTRA_PUBKEY) is the preferred route — no private key
# ever travels, and re-authorizing it here is idempotent.
touch "$AUTHORIZED_KEYS"
chmod 600 "$AUTHORIZED_KEYS"
for pub in "$CLIENT_KEY.pub" "$EXTRA_PUBKEY"; do
  [ -f "$pub" ] || continue
  grep -qF "$(cat "$pub")" "$AUTHORIZED_KEYS" || cat "$pub" >> "$AUTHORIZED_KEYS"
done

# --- sshd config. The distro's sshd_config has `Include sshd_config.d/*.conf` at
# the top, so these win over its later defaults.
sudo mkdir -p /etc/ssh/sshd_config.d /run/sshd
sudo tee "$DROPIN" >/dev/null <<EOF
# Generated by .devcontainer/ssh-setup.sh — rerun the script instead of editing.
Port $PORT
ListenAddress 0.0.0.0
# Keys live in the dedicated Orca volume, never in the shared home volume.
AuthorizedKeysFile $AUTHORIZED_KEYS
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin no
AllowUsers $USER_NAME
AllowTcpForwarding yes
# PAM, not because we authenticate through it (key-only), but because UsePAM no makes
# sshd reject any account whose password field is locked — which is the norm for a
# container user with no password. Account checks stay with pam_unix.
UsePAM yes
# Records offered/failed key fingerprints, so "why is it asking for a password" is
# answerable from /var/log/sshd.log instead of guesswork.
LogLevel VERBOSE
PrintMotd no
EOF
sudo chmod 644 "$DROPIN"

# The base image writes PASEO_* into /etc/environment, and pam_env.so loads that into
# every SSH session — so Orca's remote shells would otherwise inherit the daemon's
# config. Rewrite the sshd stack's bare pam_env line to read an empty file instead;
# locale still arrives via the separate line that names /etc/default/locale. The line
# is replaced wholesale because a distro trailing comment would swallow an appended
# directive. awk stops at any '#', so an already-patched line is recognised either way.
PAM_SSHD=/etc/pam.d/sshd
if [ -f "$PAM_SSHD" ]; then
  line="$(awk '/pam_env\.so/ { c = $0; sub(/#.*/, "", c); if (c !~ /envfile=/) { print NR; exit } }' "$PAM_SSHD")"
  if [ -n "${line:-}" ]; then
    sudo cp -n "$PAM_SSHD" "$PAM_SSHD.griffdive-orig"
    sudo sed -i "${line}c session    required     pam_env.so envfile=/dev/null # orca-ssh-pam-env" "$PAM_SSHD"
  fi
fi

port_open() { (exec 3<>"/dev/tcp/127.0.0.1/$PORT") 2>/dev/null; }

if ! port_open; then
  sudo /usr/sbin/sshd -t   # fail loudly on a bad config rather than starting silently
  sudo /usr/sbin/sshd -E /var/log/sshd.log
  for _ in $(seq 1 20); do
    if port_open; then break; fi
    sleep 0.25
  done
fi

if ! port_open; then
  echo "sshd failed to listen on $PORT — see /var/log/sshd.log" >&2
  exit 1
fi

echo
echo "Orca SSH target ready (container sshd on :$PORT, forwarded to your laptop)"
echo "  Host            127.0.0.1"
echo "  Port            $PORT"
echo "  User            $USER_NAME"
echo "  Host key        $(ssh-keygen -lf "$HOST_KEY_DIR/ssh_host_ed25519_key.pub" | awk '{print $2}')"
echo "  Authorized keys (fingerprint, comment):"
ssh-keygen -lf "$AUTHORIZED_KEYS" | awk '{print "    " $2 "  " $3}'
echo
echo "  State: $SSH_ROOT (own volume: survives rebuilds, independent of the home mount)"
echo "  Preferred: put your laptop's public key at .devcontainer/orca.pub."
echo "  Alternative: copy this private key to ~/.ssh/orca_griffdive on the laptop:"
echo "    $CLIENT_KEY"
