<template>
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    stroke-width="1.8"
    aria-hidden="true"
  >
    <rect
      x="3.5"
      y="3.5"
      width="17"
      height="17"
      rx="4.5"
    />
    <circle
      cx="8.3"
      cy="8.3"
      r="1.5"
      fill="currentColor"
      stroke="none"
    />
    <circle
      cx="15.7"
      cy="8.3"
      r="1.5"
      fill="currentColor"
      stroke="none"
    />
    <circle
      cx="12"
      cy="12"
      r="1.5"
      fill="currentColor"
      stroke="none"
    />
    <circle
      cx="8.3"
      cy="15.7"
      r="1.5"
      fill="currentColor"
      stroke="none"
    />
    <circle
      cx="15.7"
      cy="15.7"
      r="1.5"
      fill="currentColor"
      stroke="none"
    />
  </svg>
</template>
