import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const UPSTREAM_SHA = '9c4a8aaffd83385a2ca85d1105adfe9c9afe430b'
const REPORT_ONLY = process.argv.includes('--report')

const rootDir = join(dirname(fileURLToPath(import.meta.url)), '..')
const upstreamDir = join(rootDir, 'scripts', 'upstream')
const outDir = join(rootDir, 'shared', 'data')

const HEADER = [
  '// Generated by scripts/import-catalog.mjs — do not edit by hand.',
  `// Source: Selenestica/hd2-random-strat (MIT), vendored at scripts/upstream/.`,
  `// Upstream snapshot: ${UPSTREAM_SHA}.`,
].join('\n')

const SOURCES = [
  { file: 'primaries.js', constName: 'PRIMARIES', exportName: 'primaries', category: null },
  { file: 'secondaries.js', constName: 'SECONDARIES', exportName: 'secondaries', category: null },
  { file: 'throwables.js', constName: 'THROWABLES', exportName: 'throwables', category: null },
  { file: 'boosters.js', constName: 'BOOSTERS', exportName: 'boosters', category: null },
  { file: 'armorsets.js', constName: 'ARMOR_SETS', exportName: 'armor', category: null },
  { file: 'armorpassives.js', constName: 'ARMOR_PASSIVES', exportName: 'armorPassives', category: 'armorPassive' },
  { file: 'stratagems.js', constName: 'STRATAGEMS', exportName: 'stratagems', category: null },
]

function extractArrayLiteral(text, constName) {
  const marker = `const ${constName} = [`
  const start = text.indexOf(marker)
  if (start === -1) {
    throw new Error(`Could not find "${marker}"`)
  }
  const arrayStart = text.indexOf('[', start)
  let depth = 0
  let inString = false
  let quote = ''
  let escaped = false
  for (let i = arrayStart; i < text.length; i++) {
    const ch = text[i]
    if (inString) {
      if (escaped) {
        escaped = false
      }
      else if (ch === '\\') {
        escaped = true
      }
      else if (ch === quote) {
        inString = false
      }
      continue
    }
    if (ch === '"' || ch === '\'' || ch === '`') {
      inString = true
      quote = ch
    }
    else if (ch === '[' || ch === '{') {
      depth++
    }
    else if (ch === ']' || ch === '}') {
      depth--
      if (depth === 0) {
        return text.slice(arrayStart, i + 1)
      }
    }
  }
  throw new Error(`Unterminated array literal for ${constName}`)
}

function readRaw(file, constName) {
  const text = readFileSync(join(upstreamDir, file), 'utf8')
  return new Function(`return ${extractArrayLiteral(text, constName)}`)()
}

function toItem(raw, categoryOverride) {
  const item = {
    id: raw.internalName,
    displayName: raw.displayName,
    type: raw.type === 'Stratagem' ? 'stratagem' : 'equipment',
    category: categoryOverride ?? raw.category,
    tags: (raw.tags ?? []).filter(tag => typeof tag === 'string'),
    warbondCode: raw.warbondCode,
    tier: raw.tier,
  }
  if ('antitank' in raw) item.antitank = raw.antitank
  if ('index' in raw) item.index = raw.index
  if ('imageURL' in raw) item.imageURL = raw.imageURL
  if ('armorRating' in raw) item.armorRating = raw.armorRating
  if ('speed' in raw) item.speed = raw.speed
  if ('stamina' in raw) item.stamina = raw.stamina
  if ('passive' in raw) item.passive = raw.passive
  return item
}

function toWarbond(raw) {
  return {
    code: raw.warbondCode,
    displayName: raw.displayName,
    internalName: raw.internalName,
    imageURL: raw.imageURL,
    tier: raw.tier,
  }
}

// warbond0/1/2 have no WARBONDS entry upstream; the code -> name mapping lives
// in upstream genWarbondCheckboxes.js (acquisition channels, not warbonds).
const SPECIAL_WARBONDS = {
  warbond0: 'Super Citizen Edition',
  warbond1: 'Superstore',
  warbond2: 'Pre-Order Bonus',
}

function emitFile(fileName, headerLines, importLine, bodyLines) {
  const content = [HEADER, '', ...headerLines, '', importLine, '', ...bodyLines].join('\n')
  writeFileSync(join(outDir, fileName), `${content}\n`)
}

const report = { categories: new Set(), tags: new Set(), counts: {}, duplicateIds: [] }
const seenIds = new Set()
const converted = []

for (const source of SOURCES) {
  const rawItems = readRaw(source.file, source.constName)
  const items = rawItems.map(raw => toItem(raw, source.category))
  converted.push({ source, items })
  report.counts[source.exportName] = items.length
  for (const item of items) {
    report.categories.add(item.category)
    for (const tag of item.tags) {
      report.tags.add(tag)
    }
    if (seenIds.has(item.id)) {
      report.duplicateIds.push(item.id)
    }
    seenIds.add(item.id)
  }
}

const rawWarbonds = readRaw('warbonds.js', 'WARBONDS')
const warbondList = [
  ...Object.entries(SPECIAL_WARBONDS).map(([code, displayName]) => ({ code, displayName })),
  ...rawWarbonds.map(toWarbond),
]
report.counts.warbonds = warbondList.length
const warbondCodes = new Set(warbondList.map(w => w.code))

const unowned = converted
  .flatMap(({ items }) => items)
  .filter(item => item.warbondCode !== 'none' && !warbondCodes.has(item.warbondCode))

console.log('counts:', report.counts)
console.log('total items:', [...seenIds].length)
console.log('categories:', [...report.categories].sort())
console.log('tiers:', [...new Set(converted.flatMap(({ items }) => items.map(i => i.tier)))].sort())
console.log('duplicate ids:', report.duplicateIds)
console.log('items referencing unknown warbonds:', unowned.map(i => `${i.id} -> ${i.warbondCode}`))

if (REPORT_ONLY) {
  console.log('\nunique tags:')
  console.log([...report.tags].sort().join(', '))
  process.exit(0)
}

if (report.duplicateIds.length > 0 || unowned.length > 0) {
  console.error('\nInvariant violations — refusing to emit catalog files.')
  process.exit(1)
}

const equipmentEntries = converted.filter(({ source }) => source.file !== 'stratagems.js')
const stratagemEntry = converted.find(({ source }) => source.file === 'stratagems.js')

function emitItemExports(entries) {
  const lines = []
  for (const { source, items } of entries) {
    lines.push(`export const ${source.exportName}: Item[] = ${JSON.stringify(items, null, 2)}`)
    lines.push('')
  }
  return lines
}

emitFile(
  'equipment.ts',
  ['// Equipment: primaries, secondaries, throwables, boosters, armor, armor passives.'],
  'import type { Item } from \'./types\'',
  emitItemExports(equipmentEntries),
)

emitFile(
  'stratagems.ts',
  ['// Stratagems: supply, eagle, orbital, defense (and any other upstream categories).'],
  'import type { Item } from \'./types\'',
  [
    `export const stratagems: Item[] = ${JSON.stringify(stratagemEntry.items, null, 2)}`,
    '',
  ],
)

emitFile(
  'warbonds.ts',
  ['// Warbonds, in upstream release order.'],
  'import type { Warbond } from \'./types\'',
  [
    `export const warbonds: Warbond[] = ${JSON.stringify(warbondList, null, 2)}`,
    '',
  ],
)

console.log(`\nWrote equipment.ts, stratagems.ts, warbonds.ts to ${outDir}`)
